name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: mkdir build-toolchain

    - name: cmake
      working-directory: ./build-toolchain
      run: cmake -Dsubproject=toolchain ..

    - name: make
      working-directory: ./build-toolchain
      run: make
